# ZOOM_SCALE = 4 * 0.01
WORLD_SCALER = 1
FOODSIZE = (WORLD_SCALER * 20, WORLD_SCALER * 20)

MIN_CREATURE_SIZE = WORLD_SCALER * 10
MAX_CREATURE_SIZE = WORLD_SCALER * 30

ANTENNA_RANGE_SCALER = 3
SENSOR_RANGE = 4
MAX_ANGLE_RATE = 5
MAX_SPEED = 5

MIN_CREATURE_VIEW_DIST = WORLD_SCALER * 10
MAX_CREATURE_VIEW_DIST = WORLD_SCALER * 60
MIN_MUTATION_RATE = 0.01
MAX_MUTATION_RATE = 0.2
WORLDSIZE = (WORLD_SCALER * 1000, WORLD_SCALER * 1000)
NUM_CREATURES = 10

TORCH_SEED = 69
